// Generated by CoffeeScript 1.3.3
(function() {

  if (typeof window !== "undefined" && window !== null) {
    global = window;

  }

  if (typeof exports !== "undefined" && exports !== null) {
    global = exports;

  }

  global.requestAnimationFrame || (global.requestAnimationFrame = global.webkitRequestAnimationFrame || global.mozRequestAnimationFrame || global.oRequestAnimationFrame || global.msRequestAnimationFrame || function(callback, element) {
    return setTimeout(function() {
      return callback(+new Date())(1000 / 60);
    });
  });

}).call(this);
